poly:
    build: .
    ports: 
        - 3000:5000
    links: 
        - database
    command: bin/rake db:setup
database:
    image: convox/postgres
    ports: 
        - 5432
    volumes: 
        - /var/lib/postgresql/data
